# Generated by Django 5.1.5 on 2025-01-14 22:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_idea_image'),
        ('tools', '0003_remove_tool_icon_alter_tool_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='tool',
            field=models.ForeignKey(default=1, on_delete=models.CASCADE, to='tools.Tool'),
            preserve_default=False,
        ),
    ]
