# Generated by Django 5.1.5 on 2025-01-14 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='tools/icons/'),
            preserve_default=False,
        ),
    ]
