# Generated by Django 5.1.5 on 2025-01-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_category_alter_tool_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='icon',
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
