# Generated by Django 5.1.4 on 2025-01-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('cast', models.TextField()),
                ('rating', models.FloatField()),
                ('runtime', models.IntegerField()),
                ('review', models.TextField()),
            ],
        ),
    ]
